function blood(){
	var bloodVar="";
	bloodVar += "		<center>";
	bloodVar += "<div class=\"std\">";
	bloodVar += "";
	bloodVar += "	<div>";
	bloodVar += "	<h2>Blood Detail<\/h2>";
	bloodVar += "	<\/div>";
	bloodVar += "	<div>";
	bloodVar += "	<label>FirstName*:<\/label>";
	bloodVar += "	<input type=text id=\"sId\" placeholder=\"StudentId..\">";
	bloodVar += "	<label>LastName*:<\/label>";
	bloodVar += "	&nbsp;";
	bloodVar += "	<input type=text id=\"Name\" placeholder=\"Name..\">";
	bloodVar += "	<\/div>";
	bloodVar += "	&nbsp;&nbsp;";
	bloodVar += "	<label>BloodGroup*:<\/label>";
	bloodVar += "	&nbsp;&nbsp;&nbsp;";
	bloodVar += "	<input type=text id=\"dep\" placeholder=\"Department..!\">";
	bloodVar += " <\/div>";
	bloodVar += "	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
	bloodVar += "	<div>";
	bloodVar += "	&nbsp;&nbsp;";
	bloodVar += "	<label>MObileNumber*:<\/label>";
	bloodVar += "	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
	bloodVar += " <input type=text id=\"Year\" placeholder=\"Year..\">";
	bloodVar += "	&nbsp;&nbsp;&nbsp;&nbsp;";
	bloodVar += "	<label>Email*:<\/label>";
	bloodVar += "	&nbsp;";
	bloodVar += "	<input type=text id=\"Contact\" placeholder=\"ContactNo..\">";
	bloodVar += "	&nbsp;";
	bloodVar += "	<\/div>";
	bloodVar += "	&nbsp;&nbsp;&nbsp;";
	bloodVar += "	<div>";
	bloodVar += "	&nbsp;&nbsp;&nbsp;";
	bloodVar += "	<button id=\"submit\" >Submit</button>";
	bloodVar += "	&nbsp;";
	bloodVar += "	<button id=\"update\">GetAll</button>";
	bloodVar += "	<\/div>";
	bloodVar += "";
	bloodVar += "	<\/div>";
	bloodVar += "	</center>";
$('.blod')[0].innerHTML = bloodVar;
}