$(document).ready(function(){
    $("label").click(function(){
        $(".blod").toggle();
    });
});
$(document).ready(function(){
    $("#ads").click(function(){
        $("p").toggle();
    });
});
$(document).ready(function(){
    $("#boo").click(function(){
        $(".blods").toggle();
    });
});
$(document).ready(function(){
    $(".allbook").click(function(){
        $(".getAllbook").toggle();
    });
});