$(document).ready(function(){
    $("label").click(function(){
        $(".blod").toggle();
    });
});
$(document).ready(function(){
    $("#ads").click(function(){
        $("p").toggle();
    });
});
$(document).ready(function(){
    $("#searchs").click(function(){
        $(".getStat").toggle();
    });
});
$(document).ready(function(){
    $(".allbb").click(function(){
        $(".email").toggle();
    });
});